security:
    encoders:
        Rok\BasketBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: RokBasketBundle:User, property: imePriim }
        

    firewalls:
        login:
            pattern:  ^/(login$|css|autologin)
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                login_path: _login
                check_path: _security_check
                
        admin_area:
            pattern:    ^/admin
            http_basic: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
