<?php

namespace Rok\BasketBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ObiskTerminaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObiskTerminaRepository extends EntityRepository
{
	public function getPeopleOnTerminId($termId){
		return $this->getEntityManager()
		->createQuery(
				'SELECT p FROM RokBasketBundle:ObiskTermina p WHERE p.termin =  :tid'
		)->setParameter('tid', $termId)
		->getResult();
	}
	
	public function getUserOnTermin($userId, $termId){
		return $this->getEntityManager()
		->createQuery(
				'SELECT p FROM RokBasketBundle:ObiskTermina p WHERE p.termin =  :tid AND p.user = :uid'
		)->setParameter('tid', $termId)->setParameter('uid', $userId)
		->getResult();
	}
}
	