<?php

namespace Rok\BasketBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TerminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TerminRepository extends EntityRepository
{
	public function findAllTermins()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM RokBasketBundle:Termin p'
            )
            ->getResult();
    }
    
    public function numberOfTermins(){
    	return count($this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(p.id) FROM RokBasketBundle:Termin p'
            )
            ->getResult());
    }
}
