<?php

namespace Rok\BasketBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Rok\BasketBundle\RokBasketBundle;

/**
 * TerminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TerminRepository extends EntityRepository
{
	public function findAllTermins()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM RokBasketBundle:Termin p'
            )
            ->getResult();
    }
    
    public function numberOfTermins(){
    	return count($this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(p.id) FROM RokBasketBundle:Termin p'
            )
            ->getResult());
    }
    //and
            		//DATE_ADD(CURRENT_DATE(), 20, 'day') >= p.datum 
    public function getCurrentTermin(){
    	$id = $this->getEntityManager()
            ->createQuery(
            		"SELECT p.id FROM RokBasketBundle:Termin p 
            			WHERE p.datum >= CURRENT_DATE() 
            			ORDER BY p.datum asc"
            		)->getResult();
    	if ($id)
    		return $id[0];
    	else return 1;
    	
    }
}
