homepage:
    pattern:  /
    defaults: { _controller: RokBasketBundle:Security:login }

obiski:
    pattern:   /obiski/{id}
    defaults: { _controller: RokBasketBundle:Obisk:index, id : 1 }
    
autologin:
    pattern:  /autologin/{secret}
    defaults: { _controller: RokBasketBundle:Security:autologin }