homepage:
    pattern:  /
    defaults: { _controller: RokBasketBundle:Default:index }

obiski:
    pattern:   /obiski/{id}
    defaults: { _controller: RokBasketBundle:Obisk:index, id : 1 }
    
autologin:
    pattern:  /autologin/{secret}
    defaults: { _controller: RokBasketBundle:Security:autologin }
    
pridem:
    pattern: /pridem
    defaults: { _controller: RokBasketBundle:Obisk:pridem }
    
viewuser:
    pattern: /viewuser
    defaults: { _controller: RokBasketBundle:Security:viewUser }
    
edituser:
    pattern: /edituser
    defaults: { _controller: RokBasketBundle:Security:edituser }
    
password:
    pattern: /password
    defaults: { _controller: RokBasketBundle:Security:password }